classes:
  secretName: "telegraf-operator-classes"
  default: "influxdb_v2"
  data:
    influxdb_v2: |+
      [[outputs.influxdb_v2]]
        urls = ["https://influx.visiba.cloud"]
        token = "$TOKEN"
        organization = "Visiba"
        bucket = "telegraf-sidecar"
        timeout = "5s"
        metric_batch_size = 10000
        metric_buffer_limit = 100000
      [global_tags]
        hostname = "$HOSTNAME"
        nodename = "$NODENAME"
  certManager:
  enable: true
