kind: ConfigMap
apiVersion: v1
metadata:
  name: clamav-clamd
  namespace: clamav
data:
  clamd.conf: |
    ###############
    # General
    ###############
    # DatabaseDirectory /data
    # TemporaryDirectory /tmp
    LogTime yes
    # CUSTOM: Use pid file in tmp
    # PidFile /tmp/clamd.pid
    # LocalSocket /tmp/clamd.sock
    # CUSTOM: Set local socket group to defined group id
    #LocalSocketGroup 2000
    TCPSocket 3310
    Foreground yes
    ###############
    # Results
    ###############
    DetectPUA yes
    ExcludePUA NetTool
    ExcludePUA PWTool
    HeuristicAlerts yes
    Bytecode yes
    ###############
    # Scan
    ###############
    ScanPE yes
    DisableCertCheck yes
    ScanELF yes
    AlertBrokenExecutables yes
    ScanOLE2 yes
    ScanPDF yes
    ScanSWF yes
    ScanMail yes
    PhishingSignatures yes
    PhishingScanURLs yes
    ScanHTML yes
    ScanArchive yes
    ###############
    # Scan
    ###############
    MaxScanSize 150M
    MaxFileSize 100M
    MaxRecursion 10
    MaxFiles 15000
    MaxEmbeddedPE 10M
    MaxHTMLNormalize 10M
    MaxHTMLNoTags 2M
    MaxScriptNormalize 5M
    MaxZipTypeRcg 1M
    MaxPartitions 128
    MaxIconsPE 200
    PCREMatchLimit 10000
    PCRERecMatchLimit 10000
