apiVersion: apps/v1
kind: Deployment
metadata:
  name: clamav
  namespace: clamav
spec:
  selector:
    matchLabels:
      app: clamav
  template:
    metadata:
      labels:
        app: clamav
    spec:
      containers:
        - name: clamav
          image: mkodockx/docker-clamav:alpine
          resources:
            # limits:
            #   memory: "2G"
            #   cpu: "500m"
            # requests:
            #   memory: "64Mi"
            #   cpu: "250m"
          ports:
            - name: clamavport
              containerPort: 3310
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: clamavport
            initialDelaySeconds: 90
          readinessProbe:
            tcpSocket:
              port: clamavport
            initialDelaySeconds: 90
          volumeMounts:
            - name: freshclam-config-volume
              mountPath: /mnt/freshclam.conf
              subPath: freshclam.conf
            - name: clamd-config-volume
              mountPath: /mnt/clamd.conf
              subPath: clamd.conf
            - name: clamav-data
              mountPath: /var/lib/clamav
      volumes:
        - name: freshclam-config-volume
          configMap:
            name: clamav-freshclam
        - name: clamd-config-volume
          configMap:
            name: clamav-clamd
        - name: clamav-data
          emptyDir: {}
