apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fileserver-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
spec:
  rules:
  - host: fs1-instancename.exampledomain.topdomain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vc-fileserver
            port:
              number: 80
